spring:
  profiles:
    include: windows
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:23306/squad_only
    username: postgres
    password: root
  jpa:
    # data.sql 실행 활성화 (Spring Boot 2.5 이상 필요)
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # 테이블이 없으면 생성하고, 변경사항이 있으면 업데이트
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 20MB
#      max-request-size: 10MB

jwt:
  secret: 'your-secret-key-should-be-at-least-64-bytes-for-security-best-practices'
  expirationMs: 86400000 # 24시간
  refreshExpirationMs: 604800000 # 7일

# 초기 관리자 계정 설정
app:
  admin:
    username: admin
    password: '2345'  # 실제 환경에서는 보안을 위해 환경 변수 등으로 관리하세요
    name: squad-only
