version: '3.8'

services:
  database:
    image: postgres:17.4
    container_name: squad-only-database
    environment:
      POSTGRES_DB: squad_only
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "45432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - squad-only-network
    restart: unless-stopped

  application:
    image: ghcr.io/sggnology/squad-only:latest
    container_name: squad-only-application
    environment:
      SPRING_PROFILES_INCLUDE: linux
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/squad_only
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - squad-only-network
    restart: unless-stopped    
    volumes:
      # 호스트 디렉토리를 컨테이너에 마운트
      - ./my-app-logs:/app/logs:Z
      - ./uploads:/app/uploads:Z
    user: "1500:1500"  # UID/GID 1500으로 실행 (Dockerfile과 일치)

volumes:
  postgres_data:

networks:
  squad-only-network:
    driver: bridge